export const prompts = [
  "What's the biggest lesson you've learned from a past mistake?",
  "What's something you wish you had done differently in the past five years?",
  "If you could change one thing about the way you were raised, what would it be?",
  "What do you think is the most important quality in a friend?",
  "What's the most challenging part of being an adult?",
  "How do you stay grounded during difficult times?",
  "What do you think is the key to maintaining a healthy relationship?",
  "What's the most defining moment in your life so far?",
  "How do you define success in your own life?",
  "What's something you've had to unlearn as you've grown older?",
  "How do you handle fear or self-doubt in your life?",
  "What does your ideal future look like, and what steps are you taking to get there?",
  "What's one of the hardest things you've ever had to forgive someone for?",
  "How do you define happiness, and do you think you're currently living it?",
  "What do you value most in your relationships with others?",
  "What are you most passionate about in life, and how do you nurture that passion?",
  "What's something that's held you back from achieving your goals?",
  "How do you deal with failure, and what has it taught you?",
  "What's your biggest fear about the future, and how do you cope with it?",
  "If you could have a conversation with your future self, what would you ask?",
  "What's the most difficult personal challenge you've overcome, and how did you do it?",
  "How do you balance ambition and contentment in your life?",
  "What's the most valuable lesson you've learned from a mentor?",
  "What do you think is the meaning of life, or do you believe it has one?",
  "When was the last time you felt completely at peace with yourself?",
  "What's one decision you've made that changed your life completely?",
  "What's the most important thing you've learned about yourself over the years?",
  "How do you handle criticism, and what's the best way to give constructive feedback?",
  "What's the most significant risk you've ever taken?",
  "If you could go back in time, what advice would you give your younger self?",
  "How do you manage stress, and what techniques work best for you?",
  "What's a personal goal you've set for yourself this year, and why is it important?",
  "What's the hardest thing about being true to yourself in a world that often pressures us to conform?",
  "How do you keep yourself motivated when you're feeling discouraged?",
  "What's one thing you wish you could change about the way the world works?",
  "How do you stay connected with people who matter to you, especially when life gets busy?",
  "What does vulnerability mean to you, and how comfortable are you with it?",
  "What's one thing you've learned from a difficult relationship or experience?",
  "How do you decide what's worth fighting for in your life?",
  "What's the best piece of advice you've ever given to someone else?",
  "How do you prioritize your mental health in today's fast-paced world?",
  "What's your approach to setting boundaries, and how do you enforce them in relationships?",
  "How do you cope with loneliness or isolation, and what helps you through it?",
  "What's one area of your life that you feel you need to improve, and why?",
  "What's your biggest regret, and how do you handle it emotionally?",
  "What does personal growth look like to you, and how do you actively pursue it?",
  "What does love mean to you, and how do you express it in your relationships?",
  "What's something you've done in your life that you thought you could never do?",
  "How do you navigate moments of self-doubt, and what brings you back to confidence?",
  "How do you define trust in a relationship, and how do you rebuild it if it's broken?",
  "What's your relationship with failure, and how does it shape your decisions?",
  "What do you think is the most important thing people should learn in life?",
  "How do you handle disappointment, and what do you do to recover from it?",
  "What's one thing you feel grateful for every day?",
  "How do you maintain a sense of purpose in your daily life?",
  "What's the biggest change you've made in your life recently, and what prompted it?",
  "How do you deal with loss, and what has it taught you about resilience?",
  "How do you distinguish between what you want and what you need in life?",
  "What's one belief or value that you've held for a long time that has shaped who you are?",
  "How do you manage your emotions in difficult situations?",
  "What's one piece of advice you would give to someone going through a tough time?",
  "How do you stay true to your beliefs when they are challenged by others?",
  "What's the most courageous thing you've ever done, and how did it feel?",
  "How do you make important life decisions, and what factors do you consider?",
  "What does being a good person mean to you, and how do you embody that?",
  "What's something that brings you a sense of inner peace or fulfillment?",
  "How do you show kindness to others, and why do you think it's important?",
  "What's the most meaningful compliment you've ever received?",
  "How do you measure personal success, and what does it look like to you?",
  "What's something that makes you feel truly alive and connected to the world?",
  "How do you handle the pressure of societal expectations, and how does it affect you?",
  "What's the most rewarding part of taking care of your mental well-being?",
  "How do you approach challenges that seem impossible to overcome?",
  "What's one thing you believe everyone should do at least once in their lifetime?",
  "What role does gratitude play in your life, and how do you practice it?",
  "How do you deal with feelings of inadequacy or imposter syndrome?",
  "What's one lesson you've learned from your parents or caregivers that you still carry with you?",
  "How do you measure your personal growth over time, and what milestones are important to you?",
  "What's the biggest misconception people have about you?",
  "What's something you wish more people understood about you?",
  "How do you define success in relationships, both romantic and platonic?",
  "What's the most significant thing you've learned from failure?",
  "How do you stay motivated when things aren't going your way?",
  "What's one way you think people can make the world a better place?",
  "What's the hardest decision you've ever had to make, and how did you approach it?",
  "How do you find balance in your life when you're juggling multiple responsibilities?",
  "What's the best thing that's ever happened to you, and how did it shape you?",
  "How do you express creativity in your life, and why is it important to you?",
  "What's the most difficult conversation you've had to have with someone?",
  "What's something you'd like to change about the way people view mental health?",
  "How do you stay connected to your values when faced with external pressure?",
  "What's your biggest challenge in maintaining personal growth, and how do you overcome it?",
  "How do you handle conflicts in relationships, and what do you think is the key to resolution?",
  "What's the most important thing you've learned from someone you don't agree with?",
  "What's something that inspires you to be your best self?",
  "How do you prioritize self-care, and what does it look like for you?",
  "What's the best piece of advice you've ever received about love?",
  "How do you deal with situations where you feel misunderstood or misjudged?",
  "What's your personal definition of freedom, and how do you experience it in your life?",
  "What's one habit you've developed that has changed your life for the better?",
  "How do you nurture your inner peace during times of chaos?",
  "What's the hardest thing you've had to let go of, and how did you do it?",
  "How do you reflect on your past to guide your future decisions?",
  "What's something you've had to learn to accept about yourself?",
  "How do you stay connected with people who live far away?",
  "What's the most significant lesson you've learned from a friendship?",
  "How do you handle change when it comes suddenly or unexpectedly?",
  "What's the best decision you've made in your career, and why was it so impactful?",
  "How do you manage your time when juggling personal and professional priorities?",
  "What's the hardest thing you've had to forgive yourself for?",
  "How do you deal with jealousy, and how does it affect your relationships?",
  "What's the most profound experience you've had that shaped your worldview?",
  "What's the most valuable thing you've learned from your mistakes?",
  "How do you navigate uncertainty in your life?",
  "What does being a good listener mean to you, and how do you practice it?",
  "How do you cultivate patience when things aren't going according to plan?",
  "What's one thing you want to be remembered for in your life?",
  "How do you find meaning in the everyday moments of life?",
  "What's something you're really grateful for but don't express often enough?",
  "How do you create space for growth when you're feeling stuck or stagnant?",
  "What's your favorite memory from your childhood?",
  "What was school like for you when you were my age?",
  "What's one piece of advice you'd give someone my age?",
  "How did you meet your closest friends?",
  "What was your first job, and what did you learn from it?",
  "What's something you wish you had known when you were younger?",
  "What's a family tradition you enjoy?",
  "How do you stay motivated when things are tough?",
  "What's your favorite hobby, and how did you get into it?",
  "What's the most important lesson you've learned in life?",
  "How did you spend your summers when you were my age?",
  "What's the best book you've ever read, and why?",
  "What's your favorite holiday, and how did you celebrate it when you were younger?",
  "What kind of music do you enjoy, and how has your taste changed over the years?",
  "What was the world like when you were growing up, and how do you think it's different now?",
  "What's the best gift you've ever received?",
  "How do you handle challenges in life, and what has helped you the most?",
  "What was your dream job when you were younger?",
  "How do you relax and unwind after a busy day?",
  "What's the most exciting adventure you've ever been on?",
  "What's your favorite family memory?",
  "How did you make friends when you were younger, and how is it different now?",
  "What are you most proud of in your life?",
  "How has technology changed the way you live your life?",
  "What's something you've always wanted to try but haven't yet?",
  "What was your first car, and how did you feel when you got it?",
  "How did you celebrate birthdays when you were a kid?",
  "What's the best meal you've ever had?",
  "How do you feel about the idea of traveling the world?",
  "What's one habit you think is important for a happy life?",
  "What's something that always makes you laugh?",
  "What was your favorite subject in school, and why?",
  "What do you enjoy most about spending time with your family?",
  "What's the most difficult decision you've had to make in your life?",
  "How do you keep in touch with old friends or family who live far away?",
  "What's a skill or talent you have that you're proud of?",
  "How did you spend your free time when you were my age?",
  "What's the best advice someone ever gave you?",
  "How do you define success in your life?",
  "What's one thing you'd like to see change in the world?",
  "What's your favorite way to spend a Saturday afternoon?",
  "How did you first learn to drive, and what was it like?",
  "What's something you've learned from your mistakes?",
  "What's a story from your past that always makes you smile?",
  "How do you deal with tough situations and keep going?",
  "What's the most romantic thing you've ever done or experienced?",
  "How do you like to show people that you care about them?",
  "What's the most valuable lesson you've learned about relationships?",
  "How do you feel about the changes in the world, like the internet and social media?",
  "What's the best piece of advice you could give to the next generation?",
  "How do you like to express your creativity?",
  "What's your idea of a perfect day?",
  "What's something you've always wanted to do but haven't had the chance yet?",
  "How do you make time for the things you love?",
  "What's something you've done that made you feel proud of yourself?",
  "How do you stay positive even when things aren't going your way?",
  "What was it like growing up in your neighborhood?",
  "What's your favorite thing about your home?",
  "How did you meet your partner or spouse, and what was it like?",
  "What's something from your childhood that you wish was still around today?",
  "How do you manage your time when you have a lot to do?",
  "What's your favorite family recipe or dish?",
  "How do you celebrate the little moments in life?",
  "What's one thing you'd like to be remembered for?",
  "How has your perspective on life changed as you've gotten older?",
  "What's something you're passionate about and why?",
  "How do you think relationships have changed over the years?",
  "What do you think the future will be like for people my age?",
  "What's something that has made you feel truly appreciated?",
  "How do you like to stay active and healthy?",
  "What's your favorite memory with your parents or grandparents?",
  "How do you stay connected with the people you love, even when they're far away?",
  "What's one piece of advice you would give to your younger self?",
  "How do you make sure you take care of yourself both mentally and physically?",
  "What's your favorite way to help others or give back to your community?",
  "What's one thing that always makes you feel at peace?",
  "What's something you've learned from your experiences that you'd like to pass on?",
  "How do you stay hopeful about the future?",
  "What's the most important thing to remember when facing a big challenge?",
  "What's a tradition from your childhood that you still cherish today?",
  "How do you celebrate accomplishments, big or small?",
  "What's the most fun thing you've done in the last year?",
  "What's the best thing about growing up in your time period?",
  "What's something you've accomplished that you never thought you would?",
  "How do you feel about the way society is evolving?",
  "What's your favorite memory of a family trip or vacation?",
  "How do you deal with the things that make you nervous or anxious?",
  "What's the best advice you've ever given to someone else?",
  "How do you stay optimistic in difficult times?",
  "What's your favorite part about being part of a family?",
  "How do you keep your mind sharp and active as you age?",
  "What's the most meaningful compliment you've ever received?",
  "How do you express your love or appreciation for someone?",
  "What's the most interesting thing you've learned in your life?",
  "What's something that makes you feel nostalgic?",
  "What's one thing that always makes you smile?",
  "How do you deal with disappointment or setbacks?",
  "What's the most adventurous thing you've done, and would you do it again?",
  "What's the best trip you've ever been on, and what made it so special?",
  "How do you find joy in the simple things in life?",
]
